### ISSUE TITLE
Crash on tab-completion when line contains an opening parens "("

### ISSUE THREAD

**Issue by sharkdp** [jcubic/jquery.terminal#321]
### Expected behavior

Tab-completion results are displayed.

### Actual behavior

```
[TERMINAL]: Invalid regular expression: /^\?(/: Unterminated group
SyntaxError: Invalid regular expression: /^\?(/: Unterminated group
    at RegExp (<anonymous>)
    at r.fn.init.complete (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4860:29)
    at r.fn.init.complete (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:5905:32)
    at r.fn.init.TAB (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4389:34)
    at https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4222:40
    at Object.TAB (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:1811:40)
    at HTMLHtmlElement.keydown_event (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:2030:41)
    at HTMLHtmlElement.dispatch (https://code.jquery.com/jquery-3.1.1.min.js:3:10315)
    at HTMLHtmlElement.q.handle (https://code.jquery.com/jquery-3.1.1.min.js:3:8342)
[USER KEYMAP]: Invalid regular expression: /^\?(/: Unterminated group
SyntaxError: Invalid regular expression: /^\?(/: Unterminated group
    at RegExp (<anonymous>)
    at r.fn.init.complete (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4860:29)
    at r.fn.init.complete (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:5905:32)
    at r.fn.init.TAB (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4389:34)
    at https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:4222:40
    at Object.TAB (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:1811:40)
    at HTMLHtmlElement.keydown_event (https://rawgit.com/jcubic/jquery.terminal/master/js/jquery.terminal.js:2030:41)
    at HTMLHtmlElement.dispatch (https://code.jquery.com/jquery-3.1.1.min.js:3:10315)
    at HTMLHtmlElement.q.handle (https://code.jquery.com/jquery-3.1.1.min.js:3:8342)
```

### Steps to reproduce

Go to codepen http://codepen.io/jcubic/pen/MbVMwO and enter

``` js
// for browsers that don't support key property
keyboardeventKeyPolyfill.polyfill();

var term = $('body').terminal(
    function() {},
    { completion: ["foo", "bar"] }
);
```

Then, type `(` in the terminal and press tab.

**Comment by jcubic** [comment]
Fixed in devel branch, the problem was with escaping, if you need fix right now you can turn off escaping using option:

```javascript
{
  completionEscape: false
}
```

You can test it here https://codepen.io/jcubic/pen/LxgJQG

**Comment by sharkdp** [comment]
Oh, thank you very much! Your response time is incredible :+1: :smile: 

*(used the workaround for insect)*

**Comment by jcubic** [comment]
In version 1.5.0
